spring:
  jms:
    template:
      default-destination: taco.order.queue
  artemis:
    host: localhost
    port: 61616
    user: tacoweb
    password: jms1msg
    embedded:
      enabled: false

---
spring:
  profiles: production

  artemis:
    host: artemis.taco.com
    port: 61617
    user: tacoweb
    password: jms1msg